In [1]:
!pip install numpy

'pip'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.


In [2]:
import numpy as np

In [3]:
num1 = [1,2,3,4]
num2 = [5,6,7,8]

num = [num1, num2]

num

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [4]:
num1 + num2

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
num1 = np.array(num1)
num2 = np.array(num2)

num1

array([1, 2, 3, 4])

In [8]:
num1 + num2

array([ 6,  8, 10, 12])

In [9]:
num1.sum()

np.int64(10)

In [11]:
num = np.array([num1, num2])

num

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
num.shape

(2, 4)

In [14]:
num[1,3]

np.int64(8)

In [16]:
num3 = num[:2, :2]
num3

array([[1, 2],
       [5, 6]])

In [17]:
num3 = num[0:, 1:]
num3

array([[2, 3, 4],
       [6, 7, 8]])

In [18]:
num.sum(axis=0)

array([ 6,  8, 10, 12])

In [19]:
num.sum(axis=1)

array([10, 26])